import type { WidgetSchema } from '../descriptor';

export const textSchema: WidgetSchema = [
  { key: 'text', label: 'Text', group: 'Text', control: 'text', default: '',
    flutter: { target: 'Text.data' } },
  { key: 'fontFamily', label: 'Font', group: 'Text', control: 'dropdown',
    options: ['Poppins', 'Montserrat'], default: 'Poppins',
    flutter: { target: 'TextStyle.fontFamily' } },
  { key: 'fontSize', label: 'Size', group: 'Text', control: 'number', min: 1, step: 1,
    default: 13, responsive: true, flutter: { target: 'TextStyle.fontSize' } },
  { key: 'fontWeight', label: 'Weight', group: 'Text', control: 'dropdown',
    options: ['400', '500', '600', '700', '800'], default: '400',
    flutter: { target: 'TextStyle.fontWeight' } },
  { key: 'color', label: 'Color', group: 'Text', control: 'color', default: '#1A1C17',
    flutter: { target: 'TextStyle.color' } },
  { key: 'letterSpacing', label: 'Letter spacing', group: 'Text', control: 'number',
    step: 0.1, default: 0, flutter: { target: 'TextStyle.letterSpacing' } },
  { key: 'height', label: 'Line height', group: 'Text', control: 'number', min: 0.8,
    step: 0.05, default: 1.5, flutter: { target: 'TextStyle.height' } },
  { key: 'textAlign', label: 'Align', group: 'Text', control: 'dropdown',
    options: ['left', 'center', 'right', 'justify'], default: 'left',
    flutter: { target: 'Text.textAlign' } },
  { key: 'maxLines', label: 'Max lines', group: 'Text', control: 'number', min: 1, step: 1,
    default: 0, flutter: { target: 'Text.maxLines', note: '0 = unlimited' } },
];
